name: manycards
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.de

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  page_transition: ^2.2.1
  liquid_pull_to_refresh: ^3.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  http: ^1.3.0
  intl: ^0.20.2
  provider: ^6.1.4
  shimmer: ^3.0.0
  flutter_swiper_view: ^1.1.8
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.4.15

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/svg/

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true # ✅ Kept only supported integrations

  assets:
    enabled: true

  fonts:
    enabled: true
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
